spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/heth
    username: sa
    password:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
logging:
  level:
    p6spy: info